blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='blog'

urlpatterns=[
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete= models.CASCADE)
    title = models.CharField(max_length=70)
    content = models.TextField()
    created_date = models.DateTimeField(default= timezone.now)
    pub_date = models.DateTimeField(blank= True, null= True)

    def publish(self):
        self.pub_date= timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'content')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from  .models import Post
from .forms import PostForm
from django.utils import timezone

def post_list(request):
    posts = Post.objects.order_by('pub_date')
    return render(request,'blog/post_list.html', {'posts':posts})


def post_detail(request, pk):
    post= get_object_or_404(Post, pk= pk)
    return render(request, 'blog/post_detail.html', {'post': post})


def post_new(request):
    if request.method== 'POST':
        form= PostForm(request.POST)
        if form.is_valid():
            post= form.save(commit=False)
            post.author= request.user
            post.save()
            return redirect('blog:post_detail',pk=post.pk)
    else:
        form= PostForm()
        return render(request, 'blog/post_edit.html', {'form':form})

def post_edit(request, pk):
    post= get_object_or_404(Post, pk=pk)
    if request.method== 'POST':
        form= PostForm(request.POST, instance=post)
        if form.is_valid():
            post= form.save(commit=False)
            post.author= request.user
            post.save()
            return redirect('blog:post_detail', pk=post.id)
    else:
        form= PostForm(instance=post)
        return render(request, 'blog/post_edit.html', {'form':form})

def post_draft_list(request):
    posts=Post.objects.filter(pub_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})


def post_publish(request, pk):
    post=get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

def post_remove(request, pk):
    post= get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

blog/templates/blog/base.html
{% load static %}

<head>
    <title>My Blog</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="page-header">
        <h1><a href="/">Django Girls Blog</a></h1>
        {% if user.is_authenticated  %}
            <a href="{% url 'blog:post_draft_list' %}" style="margin-top: -22px" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
            <a href="{% url 'blog:post_new' %}" style="margin-top: -22px" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.pub_date %}
            <div class="date">
                {{ post.pub_date }}
            </div>
        {% else %}
            <a style="float: right;margin-left: 3px"  class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a style="float: right; margin-left: 2px" class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            <a style="float: right " class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.content|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% if posts %}
        {% for post in posts %}
            <div class="post">
                <p class="date">created: {{ post.created_date}}</p>
                <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                <p>{{ post.content}}</p>
            </div>
        {% endfor %}
    {% else %}
        <h3>NO post to edit. All are published</h3>
    {% endif %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="post" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html'  %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                <p>published: {{ post.pub_date }}</p>
            </div>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.content|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}